import { VISUALIZER_CANVAS_HEIGHT, VISUALIZER_CANVAS_WIDTH } from '../../page.consts';

export const VISUALIZER_NODE_RADIUS = 12;
export const VISUALIZER_ARROW_ALIGN = 'center';
export const VISUALIZER_ARROW_BASELINE = 'middle';
export const VISUALIZER_ARROW_COLOR = '#e5e5e5';
export const VISUALIZER_ARROW_FONT = `${VISUALIZER_NODE_RADIUS * 1.2}px Arial`;
export const VISUALIZER_INNER_MARGIN = 40;
export const VISUALIZER_INNER_HEIGHT = VISUALIZER_CANVAS_HEIGHT - VISUALIZER_INNER_MARGIN * 2;
export const VISUALIZER_INNER_WIDTH = VISUALIZER_CANVAS_WIDTH - VISUALIZER_INNER_MARGIN * 2;
export const VISUALIZER_INNER_POSITION_LEFT = VISUALIZER_INNER_MARGIN;
export const VISUALIZER_INNER_POSITION_RIGHT =
  VISUALIZER_INNER_POSITION_LEFT + VISUALIZER_INNER_WIDTH;
export const VISUALIZER_INNER_POSITION_TOP = VISUALIZER_INNER_MARGIN;
export const VISUALIZER_LINE_WIDTH = 2;
